default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mailboxer-example_development

test:
  <<: *default
  database: mailboxer-example_test

production:
  <<: *default
  database: mailboxer-example_production
